version: "3.8"

services: 
  postgres:
    image: postgres:14.2
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password1;
      - POSTGRES_DB=demo-db
    ports: 
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "password1;"
    ports:
      - "8032:80"
    depends_on: 
      - postgres 
